---
# Title: role-zabbix-5-lts
#
# Author: bitfinity-nl
# File: tasks/main.yml
#
# Description:
#   Playbook for deploying Zabbix 5.0LTS 
#

- name: "Zabbix server (Ubuntu)"
  import_tasks: server/zabbix-server.yml
  when:
    - ansible_distribution_version == "20.04"
    - ansible_architecture == "x86_64"
    - zbx_type == 'server'

- name: "Zabbix Agent (Ubuntu)"
  import_tasks: agent/zbx-agent-ubt-generic.yml
  when:
    - ansible_architecture == "x86_64"
    - zbx_type == 'agent'

- name: "Zabbix Agent (Windows 64bit)"
  import_tasks: agent/windows/zbx-agent-win-64bit.yml
  when:
    - ansible_os_family == "Windows"
    - ansible_architecture == "64-bit"
    - zbx_type == 'agent'
