----
# Title: role-zabbix-5-lts
#
# Author: bitfinity-nl
# File: tasks/agent/zbx-agent-ubt-2004.yml
#
# Description:
#   Playbook for deploying Zabbix 5.0LTS 
#

- name: "Download & Install deb package"
  apt:
    deb: "{{ zbx_repository }}"
    state: present

- name: "Install Zabbix-agent"
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: "Configure Zabbix-agent"
  template:
    src:  agent/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    backup: yes
  notify:
    - restart_zabbix_agent

- name: "enable zabbix agent on startup"
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes

- name: "Allow traffic from Zabbix server to Zabbix Agent (Passive) on port 10050/tcp"
  ufw:
    rule: allow
    port: "10050"
    proto: tcp
    from_ip: "{{ zbx_agt_Server }}"

- name: "Allow traffic from Zabbix agent to Zabbix server (Active) on port 10051/tcp"
  ufw:
    rule: allow
    port: "10051"
    proto: tcp
    to_ip: "{{ zbx_agt_ServerActive }}"
